# Generated by Django 5.0.2 on 2024-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='images',
            field=models.ImageField(upload_to='photos/products'),
        ),
    ]
